name: View CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: |
        cd view
        npm install
        npm run build

    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v19
      with:
        vercel-token: 'ZE7cdrScof0IxZFxqlfVDdVA' # Set this in your repo settings
        github-token: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub
        vercel-org-id: 'team_MsmhFNtUNexXMiW1t7AbIklC' # Set this in your repo settings
        vercel-project-id: 'to-lam-sons-projects' # Set this in your repo settings
        vercel-args: '--prod' # Deploy to production
